### PR TITLE
Strict NumberList Conversions

### LINKED ISSUE #56: List Conversion Exception Options
There could be an option that throws an exception if a conversion completely ruins a number, such as a large float or double being converted to Byte - the number ends up being completely different. When the output of the conversion is nothing like the input.

_Originally posted by @DK96-OS in https://github.com/DK96-OS/MathTools/pull/55#discussion_r812319250_

### PR DESCRIPTION
**Pull request by DK96-OS**
Add strict conversions for Number typed lists.

Validates that the conversion provides an equivalent representation, so that no information is lost.

Option is provided to ignore values that do not convert, or throw an exception.

Resolves #56

### CODE REVIEW

File: lists/src/main/java/mathtools/lists/NumberComparison.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
+package mathtools.lists;
+
+/** Comparing Number Types
+ * @author DK96-OS : 2022 */
+public final class NumberComparison {
```
Comment (DK96-OS) [inline lists/src/main/java/mathtools/lists/NumberComparison.java:5]: Good, more type comparisons (int, long, float, double).

File: lists/src/main/java/mathtools/lists/NumberListConversionStrict.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+import static mathtools.lists.NumberComparison.isEquivalent;
+
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+
+/** Numbered List Conversion functions that are strict
+ * @author DK96-OS : 2022 */
+public final class NumberListConversionStrict {
```
Comment (DK96-OS) [inline lists/src/main/java/mathtools/lists/NumberListConversionStrict.java:11]: Good, more number type support (short, int, long, float, double).

File: lists/src/test/java/mathtools/lists/NumberListConversionTest.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+import org.junit.jupiter.api.Test;
+
+import java.util.ArrayList;
+import java.util.List;
+
+/** Testing NumberList Conversion
+ * @author DK96-OS : 2022 */
+public final class NumberListConversionTest {
```
Comment (DK96-OS) [inline lists/src/test/java/mathtools/lists/NumberListConversionTest.java:12]: Type Conversion Test classes can be split up by target type - prevent files from being too large and difficult to scroll through.

**Comment by DK96-OS** [comment]
Earlier today, a serious bug was discovered in __Lists__ module #64 

This branch (lists-dev) contains updates to __Lists__ module, which are concerned with the differences between number types.

File: lists/src/main/java/mathtools/lists/NumberComparison.java (hunk 1 above)
Comment (DK96-OS) [reply lists/src/main/java/mathtools/lists/NumberComparison.java:5]: To do: #66

File: lists/src/main/java/mathtools/lists/NumberListConversionStrict.java (hunk 2 above)
Comment (DK96-OS) [reply lists/src/main/java/mathtools/lists/NumberListConversionStrict.java:13]: To do: #66

File: lists/src/test/java/mathtools/lists/NumberListConversionTest.java (hunk 3 above)
Comment (DK96-OS) [reply lists/src/test/java/mathtools/lists/NumberListConversionTest.java:12]: To do: #66
